# Application Configuration:
headersv:

  general:
    headersToIgnore:
    invBroadcastEnabled: true
    sendHeadersEnabled: true
  network:
    networkId: "regtest"
    shareP2P: "no"
    minPeers: 1
    maxPeers: 15
    initialConnections: "127.0.0.1:18444"
    genesisHeaderHex: 0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4adae5494dffff7f2002000000
    port: 18444

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600